table 'Mesures DAX'
	lineageTag: 7529060f-d758-4e99-b486-6dff4d07c63b

	measure 'Date Auto' =
			
			VAR _Date = TODAY()
			RETURN _Date
		formatString: General Date
		displayFolder: Time Intelligence
		lineageTag: 15eb63f2-5a40-4449-bec7-51da7f8b4922
		description: Date du jour dynamique pour le rafraîchissement des données.

	measure 'Frais Total TTC' =
			
			VAR _Result = CALCULATE(SUM('FACT ACTIVITES'[Montant TTC]), 'FACT ACTIVITES'[Type] = "Dépense")
			RETURN COALESCE(_Result, 0)
		displayFolder: Finance
		lineageTag: 519d9431-76dc-4b8f-8e5b-44021eb8e0c7
		description: Somme des montants TTC classés comme Dépense.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Marge =
			
			VAR _Recettes = [Recettes TTC]
			VAR _Frais = [Frais Total TTC]
			RETURN _Recettes - _Frais
		displayFolder: Finance
		lineageTag: 5a7c07ca-31e5-494d-bfdb-549a355e0a97
		description: Différence entre les recettes TTC et les frais totaux TTC.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nb Clients Convertis MTD' = ```
			
			VAR _Result = TOTALMTD(
			    CALCULATE(
			        COUNTROWS('DIM PROSPECTION'),
			        FILTER(
			            'DIM PROSPECTION',
			            RELATED('DIM CLIENTS'[ID Prospects]) <> BLANK()
			        )
			    ),
			    'DIM-Calendar'[Date]
			)
			RETURN COALESCE(_Result, 0)
			```
		formatString: 0
		displayFolder: Prospection
		lineageTag: 6cf980cc-4ebe-4e6c-b62f-0dfde9ee6eb4
		description: Nombre de prospects transformés en clients sur le mois en cours.

	measure 'Taux Transformation M-1' = ```
			
			VAR _Result = CALCULATE(
			    [Nb Clients Convertis MTD],
			    DATEADD('DIM-Calendar'[Date], -1, MONTH)
			)
			RETURN COALESCE(_Result, 0)
			```
		displayFolder: Prospection
		lineageTag: f755f450-52e9-49f3-bdb1-6549b4886b15
		description: Nombre de clients convertis (MTD) sur le mois précédent (M-1).

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nb Prospects' = ```
			
			VAR _Result = CALCULATE(
			    DISTINCTCOUNT('DIM PROSPECTION'[records.fields.ID Prospects]),
			    USERELATIONSHIP('DIM PROSPECTION'[records.fields.Date 1er contact], 'DIM-Calendar'[Date])
			)
			RETURN COALESCE(_Result, 0)
			```
		formatString: 0
		displayFolder: Prospection
		lineageTag: c1dd85c8-d274-48b6-a895-7d2a0e47b50c
		description: Nombre distinct de prospects basé sur la date de 1er contact.

	measure 'Nb Clients' =
			
			VAR _Result = CALCULATE(
			    DISTINCTCOUNT('DIM Clients'[ID Client]),
			    USERELATIONSHIP('DIM CLIENTS'[Date Création], 'DIM-Calendar'[Date])
			)
			RETURN COALESCE(_Result, 0)
		formatString: 0
		displayFolder: Clients
		lineageTag: 65ecee27-9406-4554-8d3f-a59b3216ba38
		description: Nombre distinct de clients actifs basé sur la date de création.

	measure 'Recettes TTC' = ```
			
			VAR _Result = CALCULATE(
			    SUM('FACT ACTIVITES'[Montant TTC]),
			    'FACT ACTIVITES'[Type] = "Recette"
			)
			RETURN COALESCE(_Result, 0)
			```
		displayFolder: Finance
		lineageTag: b0f26c45-001d-4273-a2b4-691ceb92dcc0
		description: Somme des montants TTC classés comme Recette.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CA Total HT YTD' =
			
			VAR _Result = TOTALYTD(
			    CALCULATE(SUM('FACT ACTIVITES'[Montant HT]), 'FACT ACTIVITES'[Catégories]="Mission"),
			    'DIM-Calendar'[Date]
			)
			RETURN COALESCE(_Result, 0)
		displayFolder: Finance
		lineageTag: 28235a32-a10a-4b47-b0a2-198dd4f2e38e
		description: Chiffre d'Affaires HT cumulé depuis le début de l'année (YTD) pour les Missions.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dépenses  Signé' = ```
			
			VAR _Result = CALCULATE(SUM('FACT ACTIVITES'[Montant TTC]), 'FACT ACTIVITES'[Type] = "Dépense") * -1
			RETURN COALESCE(_Result, 0)
			```
		displayFolder: Finance
		lineageTag: 7e411a66-9444-437a-b4a0-9379a8fe9b1a
		description: Montant négatif des dépenses TTC pour affichage comptable.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nbre jours facturés' =
			
			VAR _Result = CALCULATE(
			    SUM('DIM MISSIONS'[Nb jours facturés]),
			    USERELATIONSHIP('DIM MISSIONS'[Date de début], 'DIM-Calendar'[Date])
			)
			RETURN COALESCE(_Result, 0)
		formatString: 0
		displayFolder: Clients
		lineageTag: cc7def22-e6a2-4d52-9ded-b086d01b7755
		description: Nombre total de jours facturés pour les missions démarrées dans la période.

	measure 'Nb Jours facturés Moyen' =
			
			VAR _Jours = [Nbre jours facturés]
			VAR _NbMissions = DISTINCTCOUNT('DIM MISSIONS'[ID Missions])
			RETURN DIVIDE(_Jours, _NbMissions, 0)
		displayFolder: Clients
		lineageTag: c1ca60e7-74a3-4e57-bda3-5f9c7730e894
		description: Moyenne de jours facturés par mission.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nb de Jours Fact Moy Mois Précédent' =
			
			VAR _Result = CALCULATE([Nb Jours facturés Moyen], DATEADD('DIM-Calendar'[Date], -1, MONTH))
			RETURN COALESCE(_Result, 0)
		displayFolder: Clients
		lineageTag: 31ea7b38-4f25-47c2-829e-43decec31bff
		description: Moyenne des jours facturés sur le mois précédent.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tendance Nb Jours Fact Moyens' = ```
			
			VAR _Current = [Nb Jours facturés Moyen]
			VAR _Prev = [Nb de Jours Fact Moy Mois Précédent]
			RETURN _Current - _Prev
			```
		displayFolder: Clients
		lineageTag: 2159233d-e560-452b-80dc-7d5ec2cf53bd
		description: Variation absolue du nombre moyen de jours facturés vs mois précédent.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tendance Nb Jours Fact Moyens %' = ```
			
			VAR _Current = [Nb Jours facturés Moyen]
			VAR _Prev = [Nb de Jours Fact Moy Mois Précédent]
			RETURN
			DIVIDE(_Current - _Prev, _Prev, 0)
			```
		displayFolder: Clients
		lineageTag: 9f2e982e-7ac7-4cff-acdd-37455ba6d433
		description: Variation en pourcentage du nombre moyen de jours facturés vs mois précédent.

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CA Réalisé Graphique' =
			
			VAR _CA = [CA Total HT YTD]
			VAR _MaxDate = MAX('DIM-Calendar'[Date])
			VAR _Today = TODAY()
			RETURN
			IF(
			    _MaxDate <= _Today,
			    COALESCE(_CA, 0),
			    BLANK()
			)
		displayFolder: Finance
		lineageTag: f76b6064-0bdb-4d86-abb9-c1abb7689f0a
		description: CA YTD filtré pour ne pas afficher les projections futures (arrête à la date du jour).

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux Transformation MTD' =
			
			VAR _Clients = [Nb Clients]
			VAR _Prospects = [Nb Prospects]
			RETURN DIVIDE(_Clients, _Prospects, 0)
		displayFolder: Prospection
		lineageTag: 19af3094-17be-484e-90bd-9979b7be3d17
		description: Ratio entre le nombre de clients et le nombre de prospects (MTD).

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Colonne 1'
		dataType: string
		isHidden
		lineageTag: 0ac22e7a-7b00-4872-87ab-31591e93fb2b
		summarizeBy: none
		sourceColumn: Colonne 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Mesures DAX' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Colonne 1", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
